# Generated by Django 3.0 on 2022-08-19 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='phoneNumber',
            field=models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{11}$')], verbose_name='телефон'),
        ),
    ]
