# Generated by Django 3.0 on 2022-08-19 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_shopuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='phoneNumber',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{11}$')], verbose_name='телефон'),
        ),
    ]
