# Generated by Django 4.1.5 on 2023-03-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20221004_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='имя категории')),
                ('description', models.TextField(blank=True, verbose_name='описание категории')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активна')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Каталог категорий',
                'verbose_name_plural': 'Каталоги категорий',
            },
        ),
        migrations.AddField(
            model_name='productcategory',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.productcatalog', verbose_name='каталог категорий'),
        ),
    ]
