# Generated by Django 3.0 on 2022-07-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220713_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
