# Generated by Django 4.1.5 on 2023-03-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_productcatalog_productcategory_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalog',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
    ]
