# Generated by Django 4.1.5 on 2023-03-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_product_image_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, max_length=128, verbose_name='краткое описание продукта'),
        ),
    ]
