# Generated by Django 4.1.5 on 2023-03-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_product_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.TextField(blank=True, verbose_name='краткое описание продукта'),
        ),
    ]
